# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleMockDebugAndroidTest'
- task: CopyFiles@2
  displayName: 'Copy .apk files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: 'Archive .apk files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: apk
- task: Bash@3
  inputs:
    displayName: 'Start emulator'
    targetType: 'inline'
    script: sh ./emulator.sh
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    # publishJUnitResults: true
    # testResultsFiles: '**/TEST-*.xml'
    tasks: '-Pandroid.testInstrumentationRunnerArguments.class=com.example.android.architecture.blueprints.todoapp.test.chapter11.tests.AddToDoTest connectedMockDebugAndroidTest'
- script: mkdir $(Build.ArtifactStagingDirectory)/testResults
  condition: always()
- task: ArchiveFiles@2
  condition: always()
  inputs:
    # rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/app/reports/androidTests/connected/flavors/MOCK/' 
    rootFolderOrFile: '/Users/runner/work/1/s/app/build/reports/androidTests/connected/flavors/MOCK/'
    includeRootFolder: false 
    archiveType: 'zip' # Options: zip, 7z, tar, wim
    archiveFile: '$(Build.ArtifactStagingDirectory)/testResults/$(Build.BuildId).zip' 
    replaceExistingArchive: true 
- task: PublishBuildArtifacts@1
  displayName: 'Archive test results .zip to: $(Build.ArtifactStagingDirectory)'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/testResults'
    artifactName: test
